name: Cypress Tests

on:
  push:
    branches:
      - actions

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies - Server
        run: npm install
        working-directory: server

      - name: Install Dependencies - Web
        run: npm install
        working-directory: web

      - name: Start Server
        run: npm start
        working-directory: server

      - name: Start Web Client
        run: npm start
        working-directory: web

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install: true
