name: Testes Cypress

on:
  push:
    branches:
      - testes-cy

jobs:
  start-servers:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        server: [server, web]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Instalar Dependências - ${{ matrix.server }}
        run: npm install
        working-directory: ${{ matrix.server }}

      - name: Configurar Variável de Ambiente
        run: |
          if [ "${{ matrix.server }}" = "server" ]; then
            echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env
          fi

      - name: Iniciar ${{ matrix.server }}
        run: npm start
        working-directory: ${{ matrix.server }}
  
  wait-for-services:
    runs-on: ubuntu-latest
    needs: start-servers
    steps:
      - name: Aguardar Servidor e Cliente
        run: |
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ] && [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)" == "200" ]; do
            echo "Aguardando os serviços ficarem prontos..."
            sleep 1
          done
          echo "Os serviços estão prontos."

  run-tests:
    needs: [start-servers, wait-for-services]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Executar Testes Cypress
        uses: cypress-io/github-action@v6
        with:
          install: true
