name: Testes Cypress

on:
  push:
    branches:
      - testes-cy

jobs:
  start-server-and-client:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Instalar Dependências - Servidor
        run: npm install
        working-directory: server

      - name: Configurar Variável de Ambiente
        run: echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env

      - name: Iniciar Servidor 
        run: |
          npm start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Aguardando o servidor iniciar..."
            sleep 1
          done
          echo "Servidor iniciado com sucesso."
        working-directory: server 

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Instalar Dependências - Cliente
        run: npm install
        working-directory: web

      - name: Iniciar Cliente 
        run: |
          npm start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)" == "200" ]; do
            echo "Aguardando o cliente iniciar..."
            sleep 1
          done
          echo "Cliente iniciado com sucesso."
        working-directory: web
        
  # wait-for-services:
  #   runs-on: ubuntu-latest
  #   needs: start-server-and-client
  #   steps:
  #     - name: Aguardar Servidor e Cliente
  #       run: |
  #         until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ] && [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)" == "200" ]; do
  #           echo "Aguardando os serviços ficarem prontos..."
  #           sleep 1
  #         done
  #         echo "Os serviços estão prontos."

  run-tests:
    # needs: wait-for-services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: cypress-io/github-action@v6

      - name: Instalar Cypress
        run: npm install cypress

      - name: Executar Testes Cypress
        run: npx cypress run
