name: Testes Cypress

on:
  push:
    branches:
      - testes-cy

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Instalar Dependências - Servidor
        run: npm install 
        working-directory: server

      - name: Configurar Variável de Ambiente
        run: echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env

      - name: Iniciar Servidor 
        run: npm start &
        working-directory: server 

  start-client:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Instalar Dependências - Cliente
        run: npm install
        working-directory: web

      - name: Iniciar Cliente 
        run: npm start &
        working-directory: web
        
  run-tests:
    needs: [start-server, start-client]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: cypress-io/github-action@v6

        with: 
            wait-on: 'http://localhost:3000, http://localhost:8080'
      
      - name: Instalar Dependências
        run: npm install
        working-directory: /home/runner/work/vollmedcy/vollmedcy

      - name: Instalar Cypress
        run: npm install cypress

      - name: Executar Testes Cypress
        run: npx cypress run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
