name: Cypress Tests

on:
  push:
    branches:
      - testes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Start Server BackEnd
        # run: |
        #   cd server
        #   npm install 
        #   nohup npm start &
        run: |
          cd server
          echo "DB_ENV: ${{ secrets.DB_ENV }}" > .env  
          docker-compose up -d
          npm install 
          nohup npm start &
        env:
            SERVER_PORT: 8080

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          nohup npm start &

      - name: Write the cypress.env.json file 📝
          # use quotes around the secret, as its value
          # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
        
      - name: Wait Server

        run: |
          npx wait-on http://localhost:3000 http://localhost:8080

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6

        with:
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              
