name: Cypress Tests

on:
  push:
    branches:
      - testes-cy

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6

        with:
          start: npm run start-server, start-web-client
          wait-on: 'http://localhost:3000, http://localhost:8080'
      


    env:
      browser: chrome
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
