name: With servers
on: 
  push:
    branches:
      - testes-cy
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Server and Web
        run: |
          cd server
          npm install
          npm start &
          cd ../web
          npm install
          npm start &
      - name: Wait for servers to start
        run: sleep 30s
      - name: Cypress run
        uses: cypress-io/github-action@v6
       

   