name: Cypress Tests

on:
  push:
    branches:
      - testes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'
      - name: Show DB_ENV
        run: |
           echo 'DB_ENV: ${{ secrets.DB_ENV }}' > .env
      - name: Install Dependencies
        run: npm install
      - name: Start Server BackEnd
        run: |
          cd server
          npm install 
          nohup npm start &
      
      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          nohup npm start &

      - name: Write the cypress.env.json file
          # use quotes around the secret, as its value
          # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6

        with:
          wait-on: 'http://localhost:8080/clinica'
          # wait-on-timeout: 180
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              
