name: Cypress Tests

on:
  push:
    branches:
      - server-web

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies - Server
        run: npm install
        working-directory: server

      - name: Show DB_ENV
        run: |
          echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env
          
      - name: Start Server
        run: npm start &
        working-directory: server

      - name: Check if Server is Running
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
          if [ "$response" == "200" ]; then
            echo "Server is running successfully."
          else
            echo "Server is not running or responding with an error."
            exit 1
          fi
      

  start-web-client:
    needs: start-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencies - Web
        run: npm install
        working-directory: web

      - name: Start Web Client
        run: npm start &
        working-directory: web
      
      - name: Check if Web Client is Running
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [ "$response" == "200" ]; then
            echo "Server is running successfully."
          else
            echo "Server is not running or responding with an error."
            exit 1
          fi
